version: "3.9"

services:
  tensorflow:
    image: tensorflow/tensorflow:2.15.0-gpu
    runtime: nvidia
    ports:
      - "8888:8888"
    volumes:
      - ./:/workspace
    stdin_open: true
    tty: true