[project]
name = "deep-learning-with-python-fc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "graphviz>=0.21",
    "ipykernel>=7.2.0",
    "pydot>=4.0.1",
    "setuptools<81",
    "tensorboard>=2.20.0",
    "tensorflow>=2.21.0",
]
